version: '3'

services:

  db:
    image: mysql:9.1
    restart: always
    container_name: blogdb
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=mysql
    - MYSQL_DATABASE=blogdb
    volumes:
    - ./db:/var/lib/mysql 
  app:
    image: blog_app:1
    restart: always
    container_name: blogapp
    ports:
    - "8080:8080"
    environment:
    - FLASK_KEY=some_key
    - DB_URI=db
    - DB_SCHEMA=blogdb
    - DB_LOGIN=some_login
    - DB_PASS=some_pass
    - ADMIN_EMAIL=admin@admin.me
    - ADMIN_PASSWORD=some_pass


